[package]
name = "qrcode-generator"
version = "4.1.2"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/qrcode-generator"
homepage = "https://magiclen.org/qrcode-generator"
keywords = ["qrcode", "generate", "png", "svg", "vec"]
categories = ["no-std", "encoding", "multimedia::images"]
description = "Generate QR Code matrices and images in RAW, PNG and SVG formats."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
qrcodegen = "1.7"
html-escape = "0.2"

image-dep = { package = "image", version = "0.23.9", optional = true }

[dev-dependencies]
manifest-dir-macros = "0.1"

[features]
default = ["image"]
std = []

image = ["std", "image-dep"]

[package.metadata.docs.rs]
all-features = true